// Code generated by Kitex v0.16.3. DO NOT EDIT.

package ruleservice

import (
	"context"
	v1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/ratelimit/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListRules(ctx context.Context, Req *v1.ListRulesRequest, callOptions ...callopt.Option) (r *v1.ListRulesResponse, err error)
	CreateRule(ctx context.Context, Req *v1.CreateRuleRequest, callOptions ...callopt.Option) (r *v1.CreateRuleResponse, err error)
	UpdateRule(ctx context.Context, Req *v1.UpdateRuleRequest, callOptions ...callopt.Option) (r *v1.UpdateRuleResponse, err error)
	DeleteRule(ctx context.Context, Req *v1.DeleteRuleRequest, callOptions ...callopt.Option) (r *v1.DeleteRuleResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRuleServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRuleServiceClient struct {
	*kClient
}

func (p *kRuleServiceClient) ListRules(ctx context.Context, Req *v1.ListRulesRequest, callOptions ...callopt.Option) (r *v1.ListRulesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRules(ctx, Req)
}

func (p *kRuleServiceClient) CreateRule(ctx context.Context, Req *v1.CreateRuleRequest, callOptions ...callopt.Option) (r *v1.CreateRuleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRule(ctx, Req)
}

func (p *kRuleServiceClient) UpdateRule(ctx context.Context, Req *v1.UpdateRuleRequest, callOptions ...callopt.Option) (r *v1.UpdateRuleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRule(ctx, Req)
}

func (p *kRuleServiceClient) DeleteRule(ctx context.Context, Req *v1.DeleteRuleRequest, callOptions ...callopt.Option) (r *v1.DeleteRuleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRule(ctx, Req)
}
