// Code generated by Kitex v0.16.3. DO NOT EDIT.

package ruleservice

import (
	"context"
	"errors"
	ratelimitv1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/ratelimit/v1"
	v1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/ratelimit/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListRules": kitex.NewMethodInfo(
		listRulesHandler,
		newListRulesArgs,
		newListRulesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateRule": kitex.NewMethodInfo(
		createRuleHandler,
		newCreateRuleArgs,
		newCreateRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateRule": kitex.NewMethodInfo(
		updateRuleHandler,
		newUpdateRuleArgs,
		newUpdateRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteRule": kitex.NewMethodInfo(
		deleteRuleHandler,
		newDeleteRuleArgs,
		newDeleteRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	ruleServiceServiceInfo                = NewServiceInfo()
	ruleServiceServiceInfoForClient       = NewServiceInfoForClient()
	ruleServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return ruleServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return ruleServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return ruleServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RuleService"
	handlerType := (*ratelimitv1.RuleService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api.ratelimit.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func listRulesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListRulesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ratelimitv1.RuleService).ListRules(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListRulesArgs:
		success, err := handler.(ratelimitv1.RuleService).ListRules(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListRulesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListRulesArgs() interface{} {
	return &ListRulesArgs{}
}

func newListRulesResult() interface{} {
	return &ListRulesResult{}
}

type ListRulesArgs struct {
	Req *v1.ListRulesRequest
}

func (p *ListRulesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListRulesArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListRulesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListRulesArgs_Req_DEFAULT *v1.ListRulesRequest

func (p *ListRulesArgs) GetReq() *v1.ListRulesRequest {
	if !p.IsSetReq() {
		return ListRulesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListRulesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListRulesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListRulesResult struct {
	Success *v1.ListRulesResponse
}

var ListRulesResult_Success_DEFAULT *v1.ListRulesResponse

func (p *ListRulesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListRulesResult) Unmarshal(in []byte) error {
	msg := new(v1.ListRulesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListRulesResult) GetSuccess() *v1.ListRulesResponse {
	if !p.IsSetSuccess() {
		return ListRulesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListRulesResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListRulesResponse)
}

func (p *ListRulesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListRulesResult) GetResult() interface{} {
	return p.Success
}

func createRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateRuleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ratelimitv1.RuleService).CreateRule(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateRuleArgs:
		success, err := handler.(ratelimitv1.RuleService).CreateRule(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateRuleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateRuleArgs() interface{} {
	return &CreateRuleArgs{}
}

func newCreateRuleResult() interface{} {
	return &CreateRuleResult{}
}

type CreateRuleArgs struct {
	Req *v1.CreateRuleRequest
}

func (p *CreateRuleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateRuleArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateRuleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateRuleArgs_Req_DEFAULT *v1.CreateRuleRequest

func (p *CreateRuleArgs) GetReq() *v1.CreateRuleRequest {
	if !p.IsSetReq() {
		return CreateRuleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateRuleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateRuleResult struct {
	Success *v1.CreateRuleResponse
}

var CreateRuleResult_Success_DEFAULT *v1.CreateRuleResponse

func (p *CreateRuleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateRuleResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateRuleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateRuleResult) GetSuccess() *v1.CreateRuleResponse {
	if !p.IsSetSuccess() {
		return CreateRuleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateRuleResponse)
}

func (p *CreateRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateRuleResult) GetResult() interface{} {
	return p.Success
}

func updateRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateRuleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ratelimitv1.RuleService).UpdateRule(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateRuleArgs:
		success, err := handler.(ratelimitv1.RuleService).UpdateRule(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateRuleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateRuleArgs() interface{} {
	return &UpdateRuleArgs{}
}

func newUpdateRuleResult() interface{} {
	return &UpdateRuleResult{}
}

type UpdateRuleArgs struct {
	Req *v1.UpdateRuleRequest
}

func (p *UpdateRuleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateRuleArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateRuleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateRuleArgs_Req_DEFAULT *v1.UpdateRuleRequest

func (p *UpdateRuleArgs) GetReq() *v1.UpdateRuleRequest {
	if !p.IsSetReq() {
		return UpdateRuleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateRuleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateRuleResult struct {
	Success *v1.UpdateRuleResponse
}

var UpdateRuleResult_Success_DEFAULT *v1.UpdateRuleResponse

func (p *UpdateRuleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateRuleResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdateRuleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateRuleResult) GetSuccess() *v1.UpdateRuleResponse {
	if !p.IsSetSuccess() {
		return UpdateRuleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdateRuleResponse)
}

func (p *UpdateRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateRuleResult) GetResult() interface{} {
	return p.Success
}

func deleteRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DeleteRuleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ratelimitv1.RuleService).DeleteRule(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteRuleArgs:
		success, err := handler.(ratelimitv1.RuleService).DeleteRule(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteRuleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteRuleArgs() interface{} {
	return &DeleteRuleArgs{}
}

func newDeleteRuleResult() interface{} {
	return &DeleteRuleResult{}
}

type DeleteRuleArgs struct {
	Req *v1.DeleteRuleRequest
}

func (p *DeleteRuleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteRuleArgs) Unmarshal(in []byte) error {
	msg := new(v1.DeleteRuleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteRuleArgs_Req_DEFAULT *v1.DeleteRuleRequest

func (p *DeleteRuleArgs) GetReq() *v1.DeleteRuleRequest {
	if !p.IsSetReq() {
		return DeleteRuleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteRuleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteRuleResult struct {
	Success *v1.DeleteRuleResponse
}

var DeleteRuleResult_Success_DEFAULT *v1.DeleteRuleResponse

func (p *DeleteRuleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteRuleResult) Unmarshal(in []byte) error {
	msg := new(v1.DeleteRuleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteRuleResult) GetSuccess() *v1.DeleteRuleResponse {
	if !p.IsSetSuccess() {
		return DeleteRuleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DeleteRuleResponse)
}

func (p *DeleteRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteRuleResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListRules(ctx context.Context, Req *v1.ListRulesRequest) (r *v1.ListRulesResponse, err error) {
	var _args ListRulesArgs
	_args.Req = Req
	var _result ListRulesResult
	if err = p.c.Call(ctx, "ListRules", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateRule(ctx context.Context, Req *v1.CreateRuleRequest) (r *v1.CreateRuleResponse, err error) {
	var _args CreateRuleArgs
	_args.Req = Req
	var _result CreateRuleResult
	if err = p.c.Call(ctx, "CreateRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateRule(ctx context.Context, Req *v1.UpdateRuleRequest) (r *v1.UpdateRuleResponse, err error) {
	var _args UpdateRuleArgs
	_args.Req = Req
	var _result UpdateRuleResult
	if err = p.c.Call(ctx, "UpdateRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteRule(ctx context.Context, Req *v1.DeleteRuleRequest) (r *v1.DeleteRuleResponse, err error) {
	var _args DeleteRuleArgs
	_args.Req = Req
	var _result DeleteRuleResult
	if err = p.c.Call(ctx, "DeleteRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
