// Code generated by Kitex v0.16.3. DO NOT EDIT.

package ratelimitv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

type RateLimitRule struct {
	Id            int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PathPattern   string `protobuf:"bytes,3,opt,name=path_pattern" json:"path_pattern,omitempty"`
	Method        string `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`
	Limit         int64  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	WindowSeconds int64  `protobuf:"varint,6,opt,name=window_seconds" json:"window_seconds,omitempty"`
	Strategy      string `protobuf:"bytes,7,opt,name=strategy" json:"strategy,omitempty"`
	Enabled       bool   `protobuf:"varint,8,opt,name=enabled" json:"enabled,omitempty"`
}

func (x *RateLimitRule) Reset() { *x = RateLimitRule{} }

func (x *RateLimitRule) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RateLimitRule) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RateLimitRule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RateLimitRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RateLimitRule) GetPathPattern() string {
	if x != nil {
		return x.PathPattern
	}
	return ""
}

func (x *RateLimitRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RateLimitRule) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RateLimitRule) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *RateLimitRule) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *RateLimitRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListRulesRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListRulesRequest) Reset() { *x = ListRulesRequest{} }

func (x *ListRulesRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListRulesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListRulesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRulesResponse struct {
	Rules []*RateLimitRule `protobuf:"bytes,1,rep,name=rules" json:"rules,omitempty"`
	Total int32            `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListRulesResponse) Reset() { *x = ListRulesResponse{} }

func (x *ListRulesResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListRulesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListRulesResponse) GetRules() []*RateLimitRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ListRulesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRuleRequest struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PathPattern   string `protobuf:"bytes,2,opt,name=path_pattern" json:"path_pattern,omitempty"`
	Method        string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Limit         int64  `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	WindowSeconds int64  `protobuf:"varint,5,opt,name=window_seconds" json:"window_seconds,omitempty"`
	Strategy      string `protobuf:"bytes,6,opt,name=strategy" json:"strategy,omitempty"`
	Enabled       bool   `protobuf:"varint,7,opt,name=enabled" json:"enabled,omitempty"`
}

func (x *CreateRuleRequest) Reset() { *x = CreateRuleRequest{} }

func (x *CreateRuleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateRuleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRuleRequest) GetPathPattern() string {
	if x != nil {
		return x.PathPattern
	}
	return ""
}

func (x *CreateRuleRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateRuleRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CreateRuleRequest) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *CreateRuleRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *CreateRuleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateRuleResponse struct {
	Rule *RateLimitRule `protobuf:"bytes,1,opt,name=rule" json:"rule,omitempty"`
}

func (x *CreateRuleResponse) Reset() { *x = CreateRuleResponse{} }

func (x *CreateRuleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateRuleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateRuleResponse) GetRule() *RateLimitRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateRuleRequest struct {
	Id            int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PathPattern   string `protobuf:"bytes,3,opt,name=path_pattern" json:"path_pattern,omitempty"`
	Method        string `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`
	Limit         int64  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	WindowSeconds int64  `protobuf:"varint,6,opt,name=window_seconds" json:"window_seconds,omitempty"`
	Strategy      string `protobuf:"bytes,7,opt,name=strategy" json:"strategy,omitempty"`
	Enabled       bool   `protobuf:"varint,8,opt,name=enabled" json:"enabled,omitempty"`
}

func (x *UpdateRuleRequest) Reset() { *x = UpdateRuleRequest{} }

func (x *UpdateRuleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateRuleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRuleRequest) GetPathPattern() string {
	if x != nil {
		return x.PathPattern
	}
	return ""
}

func (x *UpdateRuleRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UpdateRuleRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *UpdateRuleRequest) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *UpdateRuleRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *UpdateRuleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateRuleResponse struct {
	Rule *RateLimitRule `protobuf:"bytes,1,opt,name=rule" json:"rule,omitempty"`
}

func (x *UpdateRuleResponse) Reset() { *x = UpdateRuleResponse{} }

func (x *UpdateRuleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateRuleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateRuleResponse) GetRule() *RateLimitRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteRuleRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *DeleteRuleRequest) Reset() { *x = DeleteRuleRequest{} }

func (x *DeleteRuleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteRuleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRuleResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *DeleteRuleResponse) Reset() { *x = DeleteRuleResponse{} }

func (x *DeleteRuleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteRuleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RuleService interface {
	ListRules(ctx context.Context, req *ListRulesRequest) (res *ListRulesResponse, err error)
	CreateRule(ctx context.Context, req *CreateRuleRequest) (res *CreateRuleResponse, err error)
	UpdateRule(ctx context.Context, req *UpdateRuleRequest) (res *UpdateRuleResponse, err error)
	DeleteRule(ctx context.Context, req *DeleteRuleRequest) (res *DeleteRuleResponse, err error)
}
