// Code generated by Kitex v0.16.3. DO NOT EDIT.

package authv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() { *x = LoginRequest{} }

func (x *LoginRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token" json:"refresh_token,omitempty"`
	ExpiresIn    int64  `protobuf:"varint,3,opt,name=expires_in" json:"expires_in,omitempty"`
}

func (x *LoginResponse) Reset() { *x = LoginResponse{} }

func (x *LoginResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshRequest struct {
	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token" json:"refresh_token,omitempty"`
}

func (x *RefreshRequest) Reset() { *x = RefreshRequest{} }

func (x *RefreshRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token" json:"refresh_token,omitempty"`
	ExpiresIn    int64  `protobuf:"varint,3,opt,name=expires_in" json:"expires_in,omitempty"`
}

func (x *RefreshResponse) Reset() { *x = RefreshResponse{} }

func (x *RefreshResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type LogoutRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *LogoutRequest) Reset() { *x = LogoutRequest{} }

func (x *LogoutRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LogoutRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LogoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LogoutResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *LogoutResponse) Reset() { *x = LogoutResponse{} }

func (x *LogoutResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LogoutResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AuthService interface {
	Login(ctx context.Context, req *LoginRequest) (res *LoginResponse, err error)
	Refresh(ctx context.Context, req *RefreshRequest) (res *RefreshResponse, err error)
	Logout(ctx context.Context, req *LogoutRequest) (res *LogoutResponse, err error)
}
