// Code generated by Kitex v0.16.3. DO NOT EDIT.

package rbacservice

import (
	"context"
	v1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/rbac/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Enforce(ctx context.Context, Req *v1.EnforceRequest, callOptions ...callopt.Option) (r *v1.EnforceResponse, err error)
	ListUsers(ctx context.Context, Req *v1.ListUsersRequest, callOptions ...callopt.Option) (r *v1.ListUsersResponse, err error)
	GetUser(ctx context.Context, Req *v1.GetUserRequest, callOptions ...callopt.Option) (r *v1.GetUserResponse, err error)
	CreateUser(ctx context.Context, Req *v1.CreateUserRequest, callOptions ...callopt.Option) (r *v1.CreateUserResponse, err error)
	UpdateUser(ctx context.Context, Req *v1.UpdateUserRequest, callOptions ...callopt.Option) (r *v1.UpdateUserResponse, err error)
	DeleteUser(ctx context.Context, Req *v1.DeleteUserRequest, callOptions ...callopt.Option) (r *v1.DeleteUserResponse, err error)
	ListRoles(ctx context.Context, Req *v1.ListRolesRequest, callOptions ...callopt.Option) (r *v1.ListRolesResponse, err error)
	CreateRole(ctx context.Context, Req *v1.CreateRoleRequest, callOptions ...callopt.Option) (r *v1.CreateRoleResponse, err error)
	UpdateRole(ctx context.Context, Req *v1.UpdateRoleRequest, callOptions ...callopt.Option) (r *v1.UpdateRoleResponse, err error)
	DeleteRole(ctx context.Context, Req *v1.DeleteRoleRequest, callOptions ...callopt.Option) (r *v1.DeleteRoleResponse, err error)
	ListPermissions(ctx context.Context, Req *v1.ListPermissionsRequest, callOptions ...callopt.Option) (r *v1.ListPermissionsResponse, err error)
	GetPermission(ctx context.Context, Req *v1.GetPermissionRequest, callOptions ...callopt.Option) (r *v1.GetPermissionResponse, err error)
	CreatePermission(ctx context.Context, Req *v1.CreatePermissionRequest, callOptions ...callopt.Option) (r *v1.CreatePermissionResponse, err error)
	UpdatePermission(ctx context.Context, Req *v1.UpdatePermissionRequest, callOptions ...callopt.Option) (r *v1.UpdatePermissionResponse, err error)
	DeletePermission(ctx context.Context, Req *v1.DeletePermissionRequest, callOptions ...callopt.Option) (r *v1.DeletePermissionResponse, err error)
	ListMenus(ctx context.Context, Req *v1.ListMenusRequest, callOptions ...callopt.Option) (r *v1.ListMenusResponse, err error)
	GetUserMenuTree(ctx context.Context, Req *v1.GetUserMenuTreeRequest, callOptions ...callopt.Option) (r *v1.GetUserMenuTreeResponse, err error)
	GetUserPermCodes(ctx context.Context, Req *v1.GetUserPermCodesRequest, callOptions ...callopt.Option) (r *v1.GetUserPermCodesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRBACServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRBACServiceClient struct {
	*kClient
}

func (p *kRBACServiceClient) Enforce(ctx context.Context, Req *v1.EnforceRequest, callOptions ...callopt.Option) (r *v1.EnforceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Enforce(ctx, Req)
}

func (p *kRBACServiceClient) ListUsers(ctx context.Context, Req *v1.ListUsersRequest, callOptions ...callopt.Option) (r *v1.ListUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, Req)
}

func (p *kRBACServiceClient) GetUser(ctx context.Context, Req *v1.GetUserRequest, callOptions ...callopt.Option) (r *v1.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, Req)
}

func (p *kRBACServiceClient) CreateUser(ctx context.Context, Req *v1.CreateUserRequest, callOptions ...callopt.Option) (r *v1.CreateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, Req)
}

func (p *kRBACServiceClient) UpdateUser(ctx context.Context, Req *v1.UpdateUserRequest, callOptions ...callopt.Option) (r *v1.UpdateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, Req)
}

func (p *kRBACServiceClient) DeleteUser(ctx context.Context, Req *v1.DeleteUserRequest, callOptions ...callopt.Option) (r *v1.DeleteUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUser(ctx, Req)
}

func (p *kRBACServiceClient) ListRoles(ctx context.Context, Req *v1.ListRolesRequest, callOptions ...callopt.Option) (r *v1.ListRolesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoles(ctx, Req)
}

func (p *kRBACServiceClient) CreateRole(ctx context.Context, Req *v1.CreateRoleRequest, callOptions ...callopt.Option) (r *v1.CreateRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRole(ctx, Req)
}

func (p *kRBACServiceClient) UpdateRole(ctx context.Context, Req *v1.UpdateRoleRequest, callOptions ...callopt.Option) (r *v1.UpdateRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRole(ctx, Req)
}

func (p *kRBACServiceClient) DeleteRole(ctx context.Context, Req *v1.DeleteRoleRequest, callOptions ...callopt.Option) (r *v1.DeleteRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRole(ctx, Req)
}

func (p *kRBACServiceClient) ListPermissions(ctx context.Context, Req *v1.ListPermissionsRequest, callOptions ...callopt.Option) (r *v1.ListPermissionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPermissions(ctx, Req)
}

func (p *kRBACServiceClient) GetPermission(ctx context.Context, Req *v1.GetPermissionRequest, callOptions ...callopt.Option) (r *v1.GetPermissionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPermission(ctx, Req)
}

func (p *kRBACServiceClient) CreatePermission(ctx context.Context, Req *v1.CreatePermissionRequest, callOptions ...callopt.Option) (r *v1.CreatePermissionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePermission(ctx, Req)
}

func (p *kRBACServiceClient) UpdatePermission(ctx context.Context, Req *v1.UpdatePermissionRequest, callOptions ...callopt.Option) (r *v1.UpdatePermissionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePermission(ctx, Req)
}

func (p *kRBACServiceClient) DeletePermission(ctx context.Context, Req *v1.DeletePermissionRequest, callOptions ...callopt.Option) (r *v1.DeletePermissionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePermission(ctx, Req)
}

func (p *kRBACServiceClient) ListMenus(ctx context.Context, Req *v1.ListMenusRequest, callOptions ...callopt.Option) (r *v1.ListMenusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMenus(ctx, Req)
}

func (p *kRBACServiceClient) GetUserMenuTree(ctx context.Context, Req *v1.GetUserMenuTreeRequest, callOptions ...callopt.Option) (r *v1.GetUserMenuTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMenuTree(ctx, Req)
}

func (p *kRBACServiceClient) GetUserPermCodes(ctx context.Context, Req *v1.GetUserPermCodesRequest, callOptions ...callopt.Option) (r *v1.GetUserPermCodesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserPermCodes(ctx, Req)
}
