// Code generated by Kitex v0.16.3. DO NOT EDIT.

package rbacservice

import (
	"context"
	"errors"
	rbacv1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/rbac/v1"
	v1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/rbac/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Enforce": kitex.NewMethodInfo(
		enforceHandler,
		newEnforceArgs,
		newEnforceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListUsers": kitex.NewMethodInfo(
		listUsersHandler,
		newListUsersArgs,
		newListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUser": kitex.NewMethodInfo(
		getUserHandler,
		newGetUserArgs,
		newGetUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateUser": kitex.NewMethodInfo(
		createUserHandler,
		newCreateUserArgs,
		newCreateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateUser": kitex.NewMethodInfo(
		updateUserHandler,
		newUpdateUserArgs,
		newUpdateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteUser": kitex.NewMethodInfo(
		deleteUserHandler,
		newDeleteUserArgs,
		newDeleteUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListRoles": kitex.NewMethodInfo(
		listRolesHandler,
		newListRolesArgs,
		newListRolesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateRole": kitex.NewMethodInfo(
		createRoleHandler,
		newCreateRoleArgs,
		newCreateRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateRole": kitex.NewMethodInfo(
		updateRoleHandler,
		newUpdateRoleArgs,
		newUpdateRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteRole": kitex.NewMethodInfo(
		deleteRoleHandler,
		newDeleteRoleArgs,
		newDeleteRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListPermissions": kitex.NewMethodInfo(
		listPermissionsHandler,
		newListPermissionsArgs,
		newListPermissionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPermission": kitex.NewMethodInfo(
		getPermissionHandler,
		newGetPermissionArgs,
		newGetPermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreatePermission": kitex.NewMethodInfo(
		createPermissionHandler,
		newCreatePermissionArgs,
		newCreatePermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdatePermission": kitex.NewMethodInfo(
		updatePermissionHandler,
		newUpdatePermissionArgs,
		newUpdatePermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeletePermission": kitex.NewMethodInfo(
		deletePermissionHandler,
		newDeletePermissionArgs,
		newDeletePermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListMenus": kitex.NewMethodInfo(
		listMenusHandler,
		newListMenusArgs,
		newListMenusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserMenuTree": kitex.NewMethodInfo(
		getUserMenuTreeHandler,
		newGetUserMenuTreeArgs,
		newGetUserMenuTreeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserPermCodes": kitex.NewMethodInfo(
		getUserPermCodesHandler,
		newGetUserPermCodesArgs,
		newGetUserPermCodesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	rBACServiceServiceInfo                = NewServiceInfo()
	rBACServiceServiceInfoForClient       = NewServiceInfoForClient()
	rBACServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return rBACServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return rBACServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return rBACServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RBACService"
	handlerType := (*rbacv1.RBACService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api.rbac.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func enforceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.EnforceRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).Enforce(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EnforceArgs:
		success, err := handler.(rbacv1.RBACService).Enforce(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EnforceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEnforceArgs() interface{} {
	return &EnforceArgs{}
}

func newEnforceResult() interface{} {
	return &EnforceResult{}
}

type EnforceArgs struct {
	Req *v1.EnforceRequest
}

func (p *EnforceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EnforceArgs) Unmarshal(in []byte) error {
	msg := new(v1.EnforceRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EnforceArgs_Req_DEFAULT *v1.EnforceRequest

func (p *EnforceArgs) GetReq() *v1.EnforceRequest {
	if !p.IsSetReq() {
		return EnforceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EnforceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EnforceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EnforceResult struct {
	Success *v1.EnforceResponse
}

var EnforceResult_Success_DEFAULT *v1.EnforceResponse

func (p *EnforceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EnforceResult) Unmarshal(in []byte) error {
	msg := new(v1.EnforceResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EnforceResult) GetSuccess() *v1.EnforceResponse {
	if !p.IsSetSuccess() {
		return EnforceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EnforceResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.EnforceResponse)
}

func (p *EnforceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EnforceResult) GetResult() interface{} {
	return p.Success
}

func listUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListUsersRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).ListUsers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListUsersArgs:
		success, err := handler.(rbacv1.RBACService).ListUsers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListUsersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListUsersArgs() interface{} {
	return &ListUsersArgs{}
}

func newListUsersResult() interface{} {
	return &ListUsersResult{}
}

type ListUsersArgs struct {
	Req *v1.ListUsersRequest
}

func (p *ListUsersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListUsersArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListUsersRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListUsersArgs_Req_DEFAULT *v1.ListUsersRequest

func (p *ListUsersArgs) GetReq() *v1.ListUsersRequest {
	if !p.IsSetReq() {
		return ListUsersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListUsersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListUsersResult struct {
	Success *v1.ListUsersResponse
}

var ListUsersResult_Success_DEFAULT *v1.ListUsersResponse

func (p *ListUsersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListUsersResult) Unmarshal(in []byte) error {
	msg := new(v1.ListUsersResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListUsersResult) GetSuccess() *v1.ListUsersResponse {
	if !p.IsSetSuccess() {
		return ListUsersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListUsersResponse)
}

func (p *ListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListUsersResult) GetResult() interface{} {
	return p.Success
}

func getUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetUserRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).GetUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserArgs:
		success, err := handler.(rbacv1.RBACService).GetUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserArgs() interface{} {
	return &GetUserArgs{}
}

func newGetUserResult() interface{} {
	return &GetUserResult{}
}

type GetUserArgs struct {
	Req *v1.GetUserRequest
}

func (p *GetUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetUserRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserArgs_Req_DEFAULT *v1.GetUserRequest

func (p *GetUserArgs) GetReq() *v1.GetUserRequest {
	if !p.IsSetReq() {
		return GetUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserResult struct {
	Success *v1.GetUserResponse
}

var GetUserResult_Success_DEFAULT *v1.GetUserResponse

func (p *GetUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserResult) Unmarshal(in []byte) error {
	msg := new(v1.GetUserResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserResult) GetSuccess() *v1.GetUserResponse {
	if !p.IsSetSuccess() {
		return GetUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetUserResponse)
}

func (p *GetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserResult) GetResult() interface{} {
	return p.Success
}

func createUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateUserRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).CreateUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateUserArgs:
		success, err := handler.(rbacv1.RBACService).CreateUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateUserArgs() interface{} {
	return &CreateUserArgs{}
}

func newCreateUserResult() interface{} {
	return &CreateUserResult{}
}

type CreateUserArgs struct {
	Req *v1.CreateUserRequest
}

func (p *CreateUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateUserArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateUserRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateUserArgs_Req_DEFAULT *v1.CreateUserRequest

func (p *CreateUserArgs) GetReq() *v1.CreateUserRequest {
	if !p.IsSetReq() {
		return CreateUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateUserResult struct {
	Success *v1.CreateUserResponse
}

var CreateUserResult_Success_DEFAULT *v1.CreateUserResponse

func (p *CreateUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateUserResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateUserResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateUserResult) GetSuccess() *v1.CreateUserResponse {
	if !p.IsSetSuccess() {
		return CreateUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateUserResponse)
}

func (p *CreateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateUserResult) GetResult() interface{} {
	return p.Success
}

func updateUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateUserRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).UpdateUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateUserArgs:
		success, err := handler.(rbacv1.RBACService).UpdateUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateUserArgs() interface{} {
	return &UpdateUserArgs{}
}

func newUpdateUserResult() interface{} {
	return &UpdateUserResult{}
}

type UpdateUserArgs struct {
	Req *v1.UpdateUserRequest
}

func (p *UpdateUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateUserArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateUserRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateUserArgs_Req_DEFAULT *v1.UpdateUserRequest

func (p *UpdateUserArgs) GetReq() *v1.UpdateUserRequest {
	if !p.IsSetReq() {
		return UpdateUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateUserResult struct {
	Success *v1.UpdateUserResponse
}

var UpdateUserResult_Success_DEFAULT *v1.UpdateUserResponse

func (p *UpdateUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateUserResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdateUserResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateUserResult) GetSuccess() *v1.UpdateUserResponse {
	if !p.IsSetSuccess() {
		return UpdateUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdateUserResponse)
}

func (p *UpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateUserResult) GetResult() interface{} {
	return p.Success
}

func deleteUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DeleteUserRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).DeleteUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteUserArgs:
		success, err := handler.(rbacv1.RBACService).DeleteUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteUserArgs() interface{} {
	return &DeleteUserArgs{}
}

func newDeleteUserResult() interface{} {
	return &DeleteUserResult{}
}

type DeleteUserArgs struct {
	Req *v1.DeleteUserRequest
}

func (p *DeleteUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteUserArgs) Unmarshal(in []byte) error {
	msg := new(v1.DeleteUserRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteUserArgs_Req_DEFAULT *v1.DeleteUserRequest

func (p *DeleteUserArgs) GetReq() *v1.DeleteUserRequest {
	if !p.IsSetReq() {
		return DeleteUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteUserResult struct {
	Success *v1.DeleteUserResponse
}

var DeleteUserResult_Success_DEFAULT *v1.DeleteUserResponse

func (p *DeleteUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteUserResult) Unmarshal(in []byte) error {
	msg := new(v1.DeleteUserResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteUserResult) GetSuccess() *v1.DeleteUserResponse {
	if !p.IsSetSuccess() {
		return DeleteUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DeleteUserResponse)
}

func (p *DeleteUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteUserResult) GetResult() interface{} {
	return p.Success
}

func listRolesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListRolesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).ListRoles(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListRolesArgs:
		success, err := handler.(rbacv1.RBACService).ListRoles(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListRolesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListRolesArgs() interface{} {
	return &ListRolesArgs{}
}

func newListRolesResult() interface{} {
	return &ListRolesResult{}
}

type ListRolesArgs struct {
	Req *v1.ListRolesRequest
}

func (p *ListRolesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListRolesArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListRolesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListRolesArgs_Req_DEFAULT *v1.ListRolesRequest

func (p *ListRolesArgs) GetReq() *v1.ListRolesRequest {
	if !p.IsSetReq() {
		return ListRolesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListRolesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListRolesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListRolesResult struct {
	Success *v1.ListRolesResponse
}

var ListRolesResult_Success_DEFAULT *v1.ListRolesResponse

func (p *ListRolesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListRolesResult) Unmarshal(in []byte) error {
	msg := new(v1.ListRolesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListRolesResult) GetSuccess() *v1.ListRolesResponse {
	if !p.IsSetSuccess() {
		return ListRolesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListRolesResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListRolesResponse)
}

func (p *ListRolesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListRolesResult) GetResult() interface{} {
	return p.Success
}

func createRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateRoleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).CreateRole(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateRoleArgs:
		success, err := handler.(rbacv1.RBACService).CreateRole(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateRoleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateRoleArgs() interface{} {
	return &CreateRoleArgs{}
}

func newCreateRoleResult() interface{} {
	return &CreateRoleResult{}
}

type CreateRoleArgs struct {
	Req *v1.CreateRoleRequest
}

func (p *CreateRoleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateRoleArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateRoleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateRoleArgs_Req_DEFAULT *v1.CreateRoleRequest

func (p *CreateRoleArgs) GetReq() *v1.CreateRoleRequest {
	if !p.IsSetReq() {
		return CreateRoleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateRoleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateRoleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateRoleResult struct {
	Success *v1.CreateRoleResponse
}

var CreateRoleResult_Success_DEFAULT *v1.CreateRoleResponse

func (p *CreateRoleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateRoleResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateRoleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateRoleResult) GetSuccess() *v1.CreateRoleResponse {
	if !p.IsSetSuccess() {
		return CreateRoleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateRoleResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateRoleResponse)
}

func (p *CreateRoleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateRoleResult) GetResult() interface{} {
	return p.Success
}

func updateRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateRoleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).UpdateRole(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateRoleArgs:
		success, err := handler.(rbacv1.RBACService).UpdateRole(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateRoleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateRoleArgs() interface{} {
	return &UpdateRoleArgs{}
}

func newUpdateRoleResult() interface{} {
	return &UpdateRoleResult{}
}

type UpdateRoleArgs struct {
	Req *v1.UpdateRoleRequest
}

func (p *UpdateRoleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateRoleArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateRoleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateRoleArgs_Req_DEFAULT *v1.UpdateRoleRequest

func (p *UpdateRoleArgs) GetReq() *v1.UpdateRoleRequest {
	if !p.IsSetReq() {
		return UpdateRoleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateRoleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateRoleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateRoleResult struct {
	Success *v1.UpdateRoleResponse
}

var UpdateRoleResult_Success_DEFAULT *v1.UpdateRoleResponse

func (p *UpdateRoleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateRoleResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdateRoleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateRoleResult) GetSuccess() *v1.UpdateRoleResponse {
	if !p.IsSetSuccess() {
		return UpdateRoleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateRoleResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdateRoleResponse)
}

func (p *UpdateRoleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateRoleResult) GetResult() interface{} {
	return p.Success
}

func deleteRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DeleteRoleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).DeleteRole(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteRoleArgs:
		success, err := handler.(rbacv1.RBACService).DeleteRole(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteRoleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteRoleArgs() interface{} {
	return &DeleteRoleArgs{}
}

func newDeleteRoleResult() interface{} {
	return &DeleteRoleResult{}
}

type DeleteRoleArgs struct {
	Req *v1.DeleteRoleRequest
}

func (p *DeleteRoleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteRoleArgs) Unmarshal(in []byte) error {
	msg := new(v1.DeleteRoleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteRoleArgs_Req_DEFAULT *v1.DeleteRoleRequest

func (p *DeleteRoleArgs) GetReq() *v1.DeleteRoleRequest {
	if !p.IsSetReq() {
		return DeleteRoleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteRoleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteRoleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteRoleResult struct {
	Success *v1.DeleteRoleResponse
}

var DeleteRoleResult_Success_DEFAULT *v1.DeleteRoleResponse

func (p *DeleteRoleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteRoleResult) Unmarshal(in []byte) error {
	msg := new(v1.DeleteRoleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteRoleResult) GetSuccess() *v1.DeleteRoleResponse {
	if !p.IsSetSuccess() {
		return DeleteRoleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteRoleResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DeleteRoleResponse)
}

func (p *DeleteRoleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteRoleResult) GetResult() interface{} {
	return p.Success
}

func listPermissionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListPermissionsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).ListPermissions(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListPermissionsArgs:
		success, err := handler.(rbacv1.RBACService).ListPermissions(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListPermissionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListPermissionsArgs() interface{} {
	return &ListPermissionsArgs{}
}

func newListPermissionsResult() interface{} {
	return &ListPermissionsResult{}
}

type ListPermissionsArgs struct {
	Req *v1.ListPermissionsRequest
}

func (p *ListPermissionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListPermissionsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListPermissionsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListPermissionsArgs_Req_DEFAULT *v1.ListPermissionsRequest

func (p *ListPermissionsArgs) GetReq() *v1.ListPermissionsRequest {
	if !p.IsSetReq() {
		return ListPermissionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListPermissionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListPermissionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListPermissionsResult struct {
	Success *v1.ListPermissionsResponse
}

var ListPermissionsResult_Success_DEFAULT *v1.ListPermissionsResponse

func (p *ListPermissionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListPermissionsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListPermissionsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListPermissionsResult) GetSuccess() *v1.ListPermissionsResponse {
	if !p.IsSetSuccess() {
		return ListPermissionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListPermissionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListPermissionsResponse)
}

func (p *ListPermissionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListPermissionsResult) GetResult() interface{} {
	return p.Success
}

func getPermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetPermissionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).GetPermission(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPermissionArgs:
		success, err := handler.(rbacv1.RBACService).GetPermission(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPermissionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPermissionArgs() interface{} {
	return &GetPermissionArgs{}
}

func newGetPermissionResult() interface{} {
	return &GetPermissionResult{}
}

type GetPermissionArgs struct {
	Req *v1.GetPermissionRequest
}

func (p *GetPermissionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPermissionArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetPermissionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPermissionArgs_Req_DEFAULT *v1.GetPermissionRequest

func (p *GetPermissionArgs) GetReq() *v1.GetPermissionRequest {
	if !p.IsSetReq() {
		return GetPermissionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPermissionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPermissionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPermissionResult struct {
	Success *v1.GetPermissionResponse
}

var GetPermissionResult_Success_DEFAULT *v1.GetPermissionResponse

func (p *GetPermissionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPermissionResult) Unmarshal(in []byte) error {
	msg := new(v1.GetPermissionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPermissionResult) GetSuccess() *v1.GetPermissionResponse {
	if !p.IsSetSuccess() {
		return GetPermissionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPermissionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetPermissionResponse)
}

func (p *GetPermissionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPermissionResult) GetResult() interface{} {
	return p.Success
}

func createPermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreatePermissionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).CreatePermission(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreatePermissionArgs:
		success, err := handler.(rbacv1.RBACService).CreatePermission(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreatePermissionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreatePermissionArgs() interface{} {
	return &CreatePermissionArgs{}
}

func newCreatePermissionResult() interface{} {
	return &CreatePermissionResult{}
}

type CreatePermissionArgs struct {
	Req *v1.CreatePermissionRequest
}

func (p *CreatePermissionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreatePermissionArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreatePermissionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreatePermissionArgs_Req_DEFAULT *v1.CreatePermissionRequest

func (p *CreatePermissionArgs) GetReq() *v1.CreatePermissionRequest {
	if !p.IsSetReq() {
		return CreatePermissionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreatePermissionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreatePermissionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreatePermissionResult struct {
	Success *v1.CreatePermissionResponse
}

var CreatePermissionResult_Success_DEFAULT *v1.CreatePermissionResponse

func (p *CreatePermissionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreatePermissionResult) Unmarshal(in []byte) error {
	msg := new(v1.CreatePermissionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreatePermissionResult) GetSuccess() *v1.CreatePermissionResponse {
	if !p.IsSetSuccess() {
		return CreatePermissionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreatePermissionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreatePermissionResponse)
}

func (p *CreatePermissionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreatePermissionResult) GetResult() interface{} {
	return p.Success
}

func updatePermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdatePermissionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).UpdatePermission(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdatePermissionArgs:
		success, err := handler.(rbacv1.RBACService).UpdatePermission(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdatePermissionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdatePermissionArgs() interface{} {
	return &UpdatePermissionArgs{}
}

func newUpdatePermissionResult() interface{} {
	return &UpdatePermissionResult{}
}

type UpdatePermissionArgs struct {
	Req *v1.UpdatePermissionRequest
}

func (p *UpdatePermissionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdatePermissionArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdatePermissionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdatePermissionArgs_Req_DEFAULT *v1.UpdatePermissionRequest

func (p *UpdatePermissionArgs) GetReq() *v1.UpdatePermissionRequest {
	if !p.IsSetReq() {
		return UpdatePermissionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdatePermissionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdatePermissionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdatePermissionResult struct {
	Success *v1.UpdatePermissionResponse
}

var UpdatePermissionResult_Success_DEFAULT *v1.UpdatePermissionResponse

func (p *UpdatePermissionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdatePermissionResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdatePermissionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdatePermissionResult) GetSuccess() *v1.UpdatePermissionResponse {
	if !p.IsSetSuccess() {
		return UpdatePermissionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdatePermissionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdatePermissionResponse)
}

func (p *UpdatePermissionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdatePermissionResult) GetResult() interface{} {
	return p.Success
}

func deletePermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DeletePermissionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).DeletePermission(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeletePermissionArgs:
		success, err := handler.(rbacv1.RBACService).DeletePermission(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeletePermissionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeletePermissionArgs() interface{} {
	return &DeletePermissionArgs{}
}

func newDeletePermissionResult() interface{} {
	return &DeletePermissionResult{}
}

type DeletePermissionArgs struct {
	Req *v1.DeletePermissionRequest
}

func (p *DeletePermissionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeletePermissionArgs) Unmarshal(in []byte) error {
	msg := new(v1.DeletePermissionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeletePermissionArgs_Req_DEFAULT *v1.DeletePermissionRequest

func (p *DeletePermissionArgs) GetReq() *v1.DeletePermissionRequest {
	if !p.IsSetReq() {
		return DeletePermissionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeletePermissionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeletePermissionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeletePermissionResult struct {
	Success *v1.DeletePermissionResponse
}

var DeletePermissionResult_Success_DEFAULT *v1.DeletePermissionResponse

func (p *DeletePermissionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeletePermissionResult) Unmarshal(in []byte) error {
	msg := new(v1.DeletePermissionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeletePermissionResult) GetSuccess() *v1.DeletePermissionResponse {
	if !p.IsSetSuccess() {
		return DeletePermissionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeletePermissionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DeletePermissionResponse)
}

func (p *DeletePermissionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeletePermissionResult) GetResult() interface{} {
	return p.Success
}

func listMenusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListMenusRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).ListMenus(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListMenusArgs:
		success, err := handler.(rbacv1.RBACService).ListMenus(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListMenusResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListMenusArgs() interface{} {
	return &ListMenusArgs{}
}

func newListMenusResult() interface{} {
	return &ListMenusResult{}
}

type ListMenusArgs struct {
	Req *v1.ListMenusRequest
}

func (p *ListMenusArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListMenusArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListMenusRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListMenusArgs_Req_DEFAULT *v1.ListMenusRequest

func (p *ListMenusArgs) GetReq() *v1.ListMenusRequest {
	if !p.IsSetReq() {
		return ListMenusArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListMenusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListMenusArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListMenusResult struct {
	Success *v1.ListMenusResponse
}

var ListMenusResult_Success_DEFAULT *v1.ListMenusResponse

func (p *ListMenusResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListMenusResult) Unmarshal(in []byte) error {
	msg := new(v1.ListMenusResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListMenusResult) GetSuccess() *v1.ListMenusResponse {
	if !p.IsSetSuccess() {
		return ListMenusResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListMenusResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListMenusResponse)
}

func (p *ListMenusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListMenusResult) GetResult() interface{} {
	return p.Success
}

func getUserMenuTreeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetUserMenuTreeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).GetUserMenuTree(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserMenuTreeArgs:
		success, err := handler.(rbacv1.RBACService).GetUserMenuTree(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserMenuTreeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserMenuTreeArgs() interface{} {
	return &GetUserMenuTreeArgs{}
}

func newGetUserMenuTreeResult() interface{} {
	return &GetUserMenuTreeResult{}
}

type GetUserMenuTreeArgs struct {
	Req *v1.GetUserMenuTreeRequest
}

func (p *GetUserMenuTreeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserMenuTreeArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetUserMenuTreeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserMenuTreeArgs_Req_DEFAULT *v1.GetUserMenuTreeRequest

func (p *GetUserMenuTreeArgs) GetReq() *v1.GetUserMenuTreeRequest {
	if !p.IsSetReq() {
		return GetUserMenuTreeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserMenuTreeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserMenuTreeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserMenuTreeResult struct {
	Success *v1.GetUserMenuTreeResponse
}

var GetUserMenuTreeResult_Success_DEFAULT *v1.GetUserMenuTreeResponse

func (p *GetUserMenuTreeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserMenuTreeResult) Unmarshal(in []byte) error {
	msg := new(v1.GetUserMenuTreeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserMenuTreeResult) GetSuccess() *v1.GetUserMenuTreeResponse {
	if !p.IsSetSuccess() {
		return GetUserMenuTreeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserMenuTreeResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetUserMenuTreeResponse)
}

func (p *GetUserMenuTreeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserMenuTreeResult) GetResult() interface{} {
	return p.Success
}

func getUserPermCodesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetUserPermCodesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rbacv1.RBACService).GetUserPermCodes(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserPermCodesArgs:
		success, err := handler.(rbacv1.RBACService).GetUserPermCodes(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserPermCodesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserPermCodesArgs() interface{} {
	return &GetUserPermCodesArgs{}
}

func newGetUserPermCodesResult() interface{} {
	return &GetUserPermCodesResult{}
}

type GetUserPermCodesArgs struct {
	Req *v1.GetUserPermCodesRequest
}

func (p *GetUserPermCodesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserPermCodesArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetUserPermCodesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserPermCodesArgs_Req_DEFAULT *v1.GetUserPermCodesRequest

func (p *GetUserPermCodesArgs) GetReq() *v1.GetUserPermCodesRequest {
	if !p.IsSetReq() {
		return GetUserPermCodesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserPermCodesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserPermCodesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserPermCodesResult struct {
	Success *v1.GetUserPermCodesResponse
}

var GetUserPermCodesResult_Success_DEFAULT *v1.GetUserPermCodesResponse

func (p *GetUserPermCodesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserPermCodesResult) Unmarshal(in []byte) error {
	msg := new(v1.GetUserPermCodesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserPermCodesResult) GetSuccess() *v1.GetUserPermCodesResponse {
	if !p.IsSetSuccess() {
		return GetUserPermCodesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserPermCodesResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetUserPermCodesResponse)
}

func (p *GetUserPermCodesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserPermCodesResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Enforce(ctx context.Context, Req *v1.EnforceRequest) (r *v1.EnforceResponse, err error) {
	var _args EnforceArgs
	_args.Req = Req
	var _result EnforceResult
	if err = p.c.Call(ctx, "Enforce", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListUsers(ctx context.Context, Req *v1.ListUsersRequest) (r *v1.ListUsersResponse, err error) {
	var _args ListUsersArgs
	_args.Req = Req
	var _result ListUsersResult
	if err = p.c.Call(ctx, "ListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUser(ctx context.Context, Req *v1.GetUserRequest) (r *v1.GetUserResponse, err error) {
	var _args GetUserArgs
	_args.Req = Req
	var _result GetUserResult
	if err = p.c.Call(ctx, "GetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateUser(ctx context.Context, Req *v1.CreateUserRequest) (r *v1.CreateUserResponse, err error) {
	var _args CreateUserArgs
	_args.Req = Req
	var _result CreateUserResult
	if err = p.c.Call(ctx, "CreateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUser(ctx context.Context, Req *v1.UpdateUserRequest) (r *v1.UpdateUserResponse, err error) {
	var _args UpdateUserArgs
	_args.Req = Req
	var _result UpdateUserResult
	if err = p.c.Call(ctx, "UpdateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUser(ctx context.Context, Req *v1.DeleteUserRequest) (r *v1.DeleteUserResponse, err error) {
	var _args DeleteUserArgs
	_args.Req = Req
	var _result DeleteUserResult
	if err = p.c.Call(ctx, "DeleteUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListRoles(ctx context.Context, Req *v1.ListRolesRequest) (r *v1.ListRolesResponse, err error) {
	var _args ListRolesArgs
	_args.Req = Req
	var _result ListRolesResult
	if err = p.c.Call(ctx, "ListRoles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateRole(ctx context.Context, Req *v1.CreateRoleRequest) (r *v1.CreateRoleResponse, err error) {
	var _args CreateRoleArgs
	_args.Req = Req
	var _result CreateRoleResult
	if err = p.c.Call(ctx, "CreateRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateRole(ctx context.Context, Req *v1.UpdateRoleRequest) (r *v1.UpdateRoleResponse, err error) {
	var _args UpdateRoleArgs
	_args.Req = Req
	var _result UpdateRoleResult
	if err = p.c.Call(ctx, "UpdateRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteRole(ctx context.Context, Req *v1.DeleteRoleRequest) (r *v1.DeleteRoleResponse, err error) {
	var _args DeleteRoleArgs
	_args.Req = Req
	var _result DeleteRoleResult
	if err = p.c.Call(ctx, "DeleteRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPermissions(ctx context.Context, Req *v1.ListPermissionsRequest) (r *v1.ListPermissionsResponse, err error) {
	var _args ListPermissionsArgs
	_args.Req = Req
	var _result ListPermissionsResult
	if err = p.c.Call(ctx, "ListPermissions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPermission(ctx context.Context, Req *v1.GetPermissionRequest) (r *v1.GetPermissionResponse, err error) {
	var _args GetPermissionArgs
	_args.Req = Req
	var _result GetPermissionResult
	if err = p.c.Call(ctx, "GetPermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatePermission(ctx context.Context, Req *v1.CreatePermissionRequest) (r *v1.CreatePermissionResponse, err error) {
	var _args CreatePermissionArgs
	_args.Req = Req
	var _result CreatePermissionResult
	if err = p.c.Call(ctx, "CreatePermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatePermission(ctx context.Context, Req *v1.UpdatePermissionRequest) (r *v1.UpdatePermissionResponse, err error) {
	var _args UpdatePermissionArgs
	_args.Req = Req
	var _result UpdatePermissionResult
	if err = p.c.Call(ctx, "UpdatePermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeletePermission(ctx context.Context, Req *v1.DeletePermissionRequest) (r *v1.DeletePermissionResponse, err error) {
	var _args DeletePermissionArgs
	_args.Req = Req
	var _result DeletePermissionResult
	if err = p.c.Call(ctx, "DeletePermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMenus(ctx context.Context, Req *v1.ListMenusRequest) (r *v1.ListMenusResponse, err error) {
	var _args ListMenusArgs
	_args.Req = Req
	var _result ListMenusResult
	if err = p.c.Call(ctx, "ListMenus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserMenuTree(ctx context.Context, Req *v1.GetUserMenuTreeRequest) (r *v1.GetUserMenuTreeResponse, err error) {
	var _args GetUserMenuTreeArgs
	_args.Req = Req
	var _result GetUserMenuTreeResult
	if err = p.c.Call(ctx, "GetUserMenuTree", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserPermCodes(ctx context.Context, Req *v1.GetUserPermCodesRequest) (r *v1.GetUserPermCodesResponse, err error) {
	var _args GetUserPermCodesArgs
	_args.Req = Req
	var _result GetUserPermCodesResult
	if err = p.c.Call(ctx, "GetUserPermCodes", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
