// Code generated by Kitex v0.16.3. DO NOT EDIT.

package rbacv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

type EnforceRequest struct {
	Sub string `protobuf:"bytes,1,opt,name=sub" json:"sub,omitempty"`
	Obj string `protobuf:"bytes,2,opt,name=obj" json:"obj,omitempty"`
	Act string `protobuf:"bytes,3,opt,name=act" json:"act,omitempty"`
}

func (x *EnforceRequest) Reset() { *x = EnforceRequest{} }

func (x *EnforceRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EnforceRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *EnforceRequest) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *EnforceRequest) GetObj() string {
	if x != nil {
		return x.Obj
	}
	return ""
}

func (x *EnforceRequest) GetAct() string {
	if x != nil {
		return x.Act
	}
	return ""
}

type EnforceResponse struct {
	Allowed bool `protobuf:"varint,1,opt,name=allowed" json:"allowed,omitempty"`
}

func (x *EnforceResponse) Reset() { *x = EnforceResponse{} }

func (x *EnforceResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EnforceResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *EnforceResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

// User messages
type User struct {
	Id       int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string   `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Active   bool     `protobuf:"varint,4,opt,name=active" json:"active,omitempty"`
	Roles    []string `protobuf:"bytes,5,rep,name=roles" json:"roles,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListUsersRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListUsersRequest) Reset() { *x = ListUsersRequest{} }

func (x *ListUsersRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUsersRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	Total int32   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListUsersResponse) Reset() { *x = ListUsersResponse{} }

func (x *ListUsersResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUsersResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetUserRequest) Reset() { *x = GetUserRequest{} }

func (x *GetUserRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *GetUserResponse) Reset() { *x = GetUserResponse{} }

func (x *GetUserResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserRequest struct {
	Username string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Email    string   `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Roles    []string `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
}

func (x *CreateUserRequest) Reset() { *x = CreateUserRequest{} }

func (x *CreateUserRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateUserRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *CreateUserResponse) Reset() { *x = CreateUserResponse{} }

func (x *CreateUserResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateUserResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	Id       int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string   `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Active   bool     `protobuf:"varint,4,opt,name=active" json:"active,omitempty"`
	Roles    []string `protobuf:"bytes,5,rep,name=roles" json:"roles,omitempty"`
}

func (x *UpdateUserRequest) Reset() { *x = UpdateUserRequest{} }

func (x *UpdateUserRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UpdateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *UpdateUserResponse) Reset() { *x = UpdateUserResponse{} }

func (x *UpdateUserResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *DeleteUserRequest) Reset() { *x = DeleteUserRequest{} }

func (x *DeleteUserRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteUserRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *DeleteUserResponse) Reset() { *x = DeleteUserResponse{} }

func (x *DeleteUserResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteUserResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Role messages
type Role struct {
	Id          int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Permissions []string `protobuf:"bytes,4,rep,name=permissions" json:"permissions,omitempty"`
}

func (x *Role) Reset() { *x = Role{} }

func (x *Role) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Role) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ListRolesRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListRolesRequest) Reset() { *x = ListRolesRequest{} }

func (x *ListRolesRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListRolesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListRolesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRolesResponse struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	Total int32   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListRolesResponse) Reset() { *x = ListRolesResponse{} }

func (x *ListRolesResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListRolesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRoleRequest struct {
	Name        string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Permissions []string `protobuf:"bytes,3,rep,name=permissions" json:"permissions,omitempty"`
}

func (x *CreateRoleRequest) Reset() { *x = CreateRoleRequest{} }

func (x *CreateRoleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateRoleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleResponse struct {
	Role *Role `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
}

func (x *CreateRoleResponse) Reset() { *x = CreateRoleResponse{} }

func (x *CreateRoleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateRoleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	Id          int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Permissions []string `protobuf:"bytes,4,rep,name=permissions" json:"permissions,omitempty"`
}

func (x *UpdateRoleRequest) Reset() { *x = UpdateRoleRequest{} }

func (x *UpdateRoleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateRoleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdateRoleResponse struct {
	Role *Role `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
}

func (x *UpdateRoleResponse) Reset() { *x = UpdateRoleResponse{} }

func (x *UpdateRoleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateRoleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *DeleteRoleRequest) Reset() { *x = DeleteRoleRequest{} }

func (x *DeleteRoleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteRoleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *DeleteRoleResponse) Reset() { *x = DeleteRoleResponse{} }

func (x *DeleteRoleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteRoleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Permission messages
type Permission struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (x *Permission) Reset() { *x = Permission{} }

func (x *Permission) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Permission) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Permission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListPermissionsRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListPermissionsRequest) Reset() { *x = ListPermissionsRequest{} }

func (x *ListPermissionsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListPermissionsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPermissionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPermissionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPermissionsResponse struct {
	Permissions []*Permission `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
	Total       int32         `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListPermissionsResponse) Reset() { *x = ListPermissionsResponse{} }

func (x *ListPermissionsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListPermissionsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPermissionRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetPermissionRequest) Reset() { *x = GetPermissionRequest{} }

func (x *GetPermissionRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPermissionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPermissionResponse struct {
	Permission *Permission `protobuf:"bytes,1,opt,name=permission" json:"permission,omitempty"`
}

func (x *GetPermissionResponse) Reset() { *x = GetPermissionResponse{} }

func (x *GetPermissionResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetPermissionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type CreatePermissionRequest struct {
	Code        string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (x *CreatePermissionRequest) Reset() { *x = CreatePermissionRequest{} }

func (x *CreatePermissionRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreatePermissionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreatePermissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePermissionResponse struct {
	Permission *Permission `protobuf:"bytes,1,opt,name=permission" json:"permission,omitempty"`
}

func (x *CreatePermissionResponse) Reset() { *x = CreatePermissionResponse{} }

func (x *CreatePermissionResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreatePermissionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionRequest struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (x *UpdatePermissionRequest) Reset() { *x = UpdatePermissionRequest{} }

func (x *UpdatePermissionRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UpdatePermissionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdatePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePermissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdatePermissionResponse struct {
	Permission *Permission `protobuf:"bytes,1,opt,name=permission" json:"permission,omitempty"`
}

func (x *UpdatePermissionResponse) Reset() { *x = UpdatePermissionResponse{} }

func (x *UpdatePermissionResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UpdatePermissionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeletePermissionRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *DeletePermissionRequest) Reset() { *x = DeletePermissionRequest{} }

func (x *DeletePermissionRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeletePermissionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeletePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePermissionResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *DeletePermissionResponse) Reset() { *x = DeletePermissionResponse{} }

func (x *DeletePermissionResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeletePermissionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeletePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Menu messages
type Menu struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Path     string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Icon     string `protobuf:"bytes,4,opt,name=icon" json:"icon,omitempty"`
	ParentId int64  `protobuf:"varint,5,opt,name=parent_id" json:"parent_id,omitempty"`
	Order    int32  `protobuf:"varint,6,opt,name=order" json:"order,omitempty"`
}

func (x *Menu) Reset() { *x = Menu{} }

func (x *Menu) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Menu) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Menu) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type ListMenusRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListMenusRequest) Reset() { *x = ListMenusRequest{} }

func (x *ListMenusRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListMenusRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListMenusRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMenusRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMenusResponse struct {
	Menus []*Menu `protobuf:"bytes,1,rep,name=menus" json:"menus,omitempty"`
	Total int32   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListMenusResponse) Reset() { *x = ListMenusResponse{} }

func (x *ListMenusResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListMenusResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListMenusResponse) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *ListMenusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserMenuTreeRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetUserMenuTreeRequest) Reset() { *x = GetUserMenuTreeRequest{} }

func (x *GetUserMenuTreeRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserMenuTreeRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserMenuTreeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserMenuTreeResponse struct {
	Menus []*Menu `protobuf:"bytes,1,rep,name=menus" json:"menus,omitempty"`
}

func (x *GetUserMenuTreeResponse) Reset() { *x = GetUserMenuTreeResponse{} }

func (x *GetUserMenuTreeResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserMenuTreeResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserMenuTreeResponse) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type GetUserPermCodesRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetUserPermCodesRequest) Reset() { *x = GetUserPermCodesRequest{} }

func (x *GetUserPermCodesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserPermCodesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserPermCodesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPermCodesResponse struct {
	PermCodes []string `protobuf:"bytes,1,rep,name=perm_codes" json:"perm_codes,omitempty"`
}

func (x *GetUserPermCodesResponse) Reset() { *x = GetUserPermCodesResponse{} }

func (x *GetUserPermCodesResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserPermCodesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserPermCodesResponse) GetPermCodes() []string {
	if x != nil {
		return x.PermCodes
	}
	return nil
}

type RBACService interface {
	Enforce(ctx context.Context, req *EnforceRequest) (res *EnforceResponse, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest) (res *ListUsersResponse, err error)
	GetUser(ctx context.Context, req *GetUserRequest) (res *GetUserResponse, err error)
	CreateUser(ctx context.Context, req *CreateUserRequest) (res *CreateUserResponse, err error)
	UpdateUser(ctx context.Context, req *UpdateUserRequest) (res *UpdateUserResponse, err error)
	DeleteUser(ctx context.Context, req *DeleteUserRequest) (res *DeleteUserResponse, err error)
	ListRoles(ctx context.Context, req *ListRolesRequest) (res *ListRolesResponse, err error)
	CreateRole(ctx context.Context, req *CreateRoleRequest) (res *CreateRoleResponse, err error)
	UpdateRole(ctx context.Context, req *UpdateRoleRequest) (res *UpdateRoleResponse, err error)
	DeleteRole(ctx context.Context, req *DeleteRoleRequest) (res *DeleteRoleResponse, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsRequest) (res *ListPermissionsResponse, err error)
	GetPermission(ctx context.Context, req *GetPermissionRequest) (res *GetPermissionResponse, err error)
	CreatePermission(ctx context.Context, req *CreatePermissionRequest) (res *CreatePermissionResponse, err error)
	UpdatePermission(ctx context.Context, req *UpdatePermissionRequest) (res *UpdatePermissionResponse, err error)
	DeletePermission(ctx context.Context, req *DeletePermissionRequest) (res *DeletePermissionResponse, err error)
	ListMenus(ctx context.Context, req *ListMenusRequest) (res *ListMenusResponse, err error)
	GetUserMenuTree(ctx context.Context, req *GetUserMenuTreeRequest) (res *GetUserMenuTreeResponse, err error)
	GetUserPermCodes(ctx context.Context, req *GetUserPermCodesRequest) (res *GetUserPermCodesResponse, err error)
}
