// Code generated by Kitex v0.16.3. DO NOT EDIT.

package authservice

import (
	"context"
	v1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/auth/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, Req *v1.LoginRequest, callOptions ...callopt.Option) (r *v1.LoginResponse, err error)
	Refresh(ctx context.Context, Req *v1.RefreshRequest, callOptions ...callopt.Option) (r *v1.RefreshResponse, err error)
	Logout(ctx context.Context, Req *v1.LogoutRequest, callOptions ...callopt.Option) (r *v1.LogoutResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) Login(ctx context.Context, Req *v1.LoginRequest, callOptions ...callopt.Option) (r *v1.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kAuthServiceClient) Refresh(ctx context.Context, Req *v1.RefreshRequest, callOptions ...callopt.Option) (r *v1.RefreshResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Refresh(ctx, Req)
}

func (p *kAuthServiceClient) Logout(ctx context.Context, Req *v1.LogoutRequest, callOptions ...callopt.Option) (r *v1.LogoutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, Req)
}
