// Code generated by Kitex v0.16.3. DO NOT EDIT.
package authservice

import (
	authv1 "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/kitex_gen/api/auth/v1"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler authv1.AuthService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler authv1.AuthService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
