// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	pb "github.com/byx-darwin/ncgo-templates/admin-bff-hertz/internal/router/pb"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	pb.Register(r)
}
